# Generated by Django 5.2.4 on 2025-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-create_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
        migrations.AddField(
            model_name="video",
            name="category",
            field=models.CharField(default="None", max_length=40),
        ),
        migrations.AddField(
            model_name="video",
            name="thumbnail_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="video",
            name="description",
            field=models.TextField(max_length=400),
        ),
    ]
