# Generated by Django 5.2.4 on 2025-07-11 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0002_alter_video_options_video_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="hls_master_playlist",
            field=models.FileField(blank=True, null=True, upload_to="hls/master/"),
        ),
        migrations.AddField(
            model_name="video",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="VideoQuality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resolution",
                    models.CharField(
                        choices=[
                            ("120p", "120p"),
                            ("360p", "360p"),
                            ("720p", "720p"),
                            ("1080p", "1080p"),
                        ],
                        max_length=10,
                    ),
                ),
                ("bitrate", models.IntegerField()),
                (
                    "hls_playlist_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="qualities",
                        to="content.video",
                    ),
                ),
            ],
            options={
                "unique_together": {("video", "resolution")},
            },
        ),
    ]
