# Generated by Django 5.2.4 on 2025-07-15 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0003_video_duration_video_hls_master_playlist_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoquality",
            name="resolution",
            field=models.CharField(
                choices=[("420p", "420p"), ("720p", "720p"), ("1080p", "1080p")],
                max_length=10,
            ),
        ),
    ]
