# Generated by Django 5.2.4 on 2025-07-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0004_alter_videoquality_resolution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
        ),
        migrations.RenameField(
            model_name="video",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
