# Generated by Django 5.2.4 on 2025-07-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0005_alter_video_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videoquality",
            name="resolution",
            field=models.CharField(
                choices=[("480p", "480p"), ("720p", "720p"), ("1080p", "1080p")],
                max_length=10,
            ),
        ),
    ]
